#!/usr/bin/env python

CLEAN = [
	'*.pyc',
    '*.gmo',
    '*.mo',
    'options.conf'
]

import os, glob
import distutils
import distutils.dir_util

for base,folders,filenames in os.walk('.'):
	if '.svn' in base:
		continue
    if '.git' in base:
        continue
	for ext in CLEAN:
		for filename in glob.glob(os.path.join(base, ext)):
			print "removing "+filename+"..."
			os.remove(filename)
distutils.dir_util.remove_tree('share')

