#encoding: utf-8

Import('env', 'install', 'install_recursive', 'win32')
import glob



install('${PIXMAPS_PATH}', 'jwsprocessor.svg', 0644)

if win32:
    install('${PIXMAPS_PATH}', 'jwsprocessor.png', 0644)

